image_path: "./NYC_1.png"
label_path: "./label_test.txt"
prompt_engineering: True
this_is: True
temperature: 100.0
use_softmax: False
run_on_gpu: True
saved_model_dir: "save_models/"
nms_threshold: 0.5
min_rpn_score_thresh: 0.9
min_box_area: 0
max_boxes_to_draw: 10
use_softmax: False
temperature: 100.0