image_path: /Users/gsq/Desktop/Other Photo/Xnip2022-03-10_09-57-42.jpg
label_path: ./label_test.txt
max_boxes_to_draw: 20
min_box_area: 0
min_rpn_score_thresh: 0.9
nms_threshold: 0.5
prompt_engineering: true
run_on_gpu: false
saved_model_dir: ./image_path_v2/
temperature: 100.0
this_is: true
use_softmax: false
